<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>14</LangVersion>
        <RootNamespace>HeatMap</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="HeatMap_DependencyProperties.cs">
        <DependentUpon>HeatMap.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
